title: Qiya Gao's Homepage
page-top-title: Qiya Gao
top-section-bg-text: Be what you wanna be
home-subtitle: Qiya Gao&ensp;|&ensp;高琪雅
copyright-text: '&copy; Qiya Gao 2023-2025. All Rights Reserved.'
